'use strict';

// season: 'all' | 'spring' | 'summer' | 'fall' | 'winter'
// spring=3-5月 summer=6-8月 fall=9-11月 winter=12-2月
// genre: '和食' | '中華' | '洋食'
// mainIngredient: '豚こま'|'豚バラ'|'豚ひき'|'豚しゃぶ'|'豚ロース'|'鶏もも'|'鶏むね'|'鶏ひき'|'手羽先'|'魚'|'豆腐'|'卵'
// estimatedPriceText は常に 'チラシ価格' （flyer 未取得時のフォールバック用）

const RECIPE_LIBRARY = [

  // ── 春（3〜5月） ─────────────────────────────────────────────────────
  {
    title: '春キャベツと豚こまの塩昆布炒め',
    season: 'spring', genre: '和食', mainIngredient: '豚こま',
    summary: 'やわらかい春キャベツに旨みが絡む、10分でまとまる一品。',
    servings: '2人前',
    estimatedTotalPrice: '',
    ingredients: [
      { name: '豚こま切れ', amount: '150', unit: 'g', countText: '1パック弱', estimatedPriceText: 'チラシ価格' },
      { name: '春キャベツ', amount: '1/4', unit: '玉', countText: '小さめ1/4', estimatedPriceText: 'チラシ価格' },
      { name: '塩昆布', amount: '大さじ1', unit: '', countText: '', estimatedPriceText: 'チラシ価格' },
    ],
    steps: [
      'キャベツはざく切り、豚こまは食べやすく切る。',
      'フライパンに油を熱し、豚こまを炒めて火を通す。',
      'キャベツを加えてしんなりするまで炒める。',
      '塩昆布を加えてさっとあえ、塩・ごま油で調整して完成。',
    ],
    reason: '春キャベツは炒めても甘みが残り、塩昆布だけで味が決まる。',
  },
  {
    title: '新玉ねぎと鶏もも肉のあっさり煮',
    season: 'spring', genre: '和食', mainIngredient: '鶏もも',
    summary: '甘い新玉ねぎが汁ごと食べられる、だし少なめの煮物。',
    servings: '2人前',
    estimatedTotalPrice: '',
    ingredients: [
      { name: '鶏もも肉', amount: '1', unit: '枚', countText: '約250g', estimatedPriceText: 'チラシ価格' },
      { name: '新玉ねぎ', amount: '2', unit: '個', countText: '大2個', estimatedPriceText: 'チラシ価格' },
    ],
    steps: [
      '鶏もも肉はひと口大に切り、玉ねぎはくし切りにする。',
      'フライパンで鶏もも肉を皮目から焼いて焼き色をつける。',
      '玉ねぎを加え、だし汁・しょうゆ・みりん各大さじ2を入れる。',
      '蓋をして中火で10分煮て、汁気を少し飛ばして盛る。',
    ],
    reason: '新玉ねぎは加熱で甘みが強くなり、余分な調味料が要らない。',
  },
  {
    title: 'アスパラと豚こまの炒め物',
    season: 'spring', genre: '和食', mainIngredient: '豚こま',
    summary: '食感のコントラストが気持ちいい、シンプルな春の炒め物。',
    servings: '2人前',
    estimatedTotalPrice: '',
    ingredients: [
      { name: '豚こま切れ', amount: '150', unit: 'g', countText: '1パック弱', estimatedPriceText: 'チラシ価格' },
      { name: 'アスパラガス', amount: '1', unit: '束', countText: '5〜6本', estimatedPriceText: 'チラシ価格' },
      { name: 'にんにく', amount: '1', unit: 'かけ', countText: '薄切り', estimatedPriceText: 'チラシ価格' },
    ],
    steps: [
      'アスパラは斜め切り、豚こまは塩こしょうで下味をつける。',
      'フライパンでにんにくを炒め、豚こまを加えて炒める。',
      'アスパラを入れてさっと炒め、オイスターソース少量で味をまとめる。',
    ],
    reason: '春のアスパラは繊維が細く、短時間の炒めでシャキッと仕上がる。',
  },
  {
    title: 'たけのこと鶏肉の煮物',
    season: 'spring', genre: '和食', mainIngredient: '鶏もも',
    summary: '水煮たけのこで手軽に。春らしい風味の定番おかず。',
    servings: '2人前',
    estimatedTotalPrice: '',
    ingredients: [
      { name: '鶏もも肉', amount: '1', unit: '枚', countText: '約250g', estimatedPriceText: 'チラシ価格' },
      { name: 'たけのこ水煮', amount: '1', unit: 'パック', countText: '約150g', estimatedPriceText: 'チラシ価格' },
      { name: '絹さや', amount: '適量', unit: '', countText: 'あれば', estimatedPriceText: 'チラシ価格' },
    ],
    steps: [
      '鶏肉はひと口大に切り、たけのこは薄切りにする。',
      'だし汁・しょうゆ・みりん・砂糖で煮汁を作り、鶏肉とたけのこを煮る。',
      '10分ほど煮て味がしみたら絹さやを加えてさっと煮て完成。',
    ],
    reason: 'たけのこは水煮を使えば下処理なしで即使える。',
  },
  {
    title: '菜の花と厚揚げの煮浸し',
    season: 'spring', genre: '和食', mainIngredient: '豆腐',
    summary: 'ほろ苦さと旨みがやさしくまとまる、春の副菜。',
    servings: '2人前',
    estimatedTotalPrice: '',
    ingredients: [
      { name: '菜の花', amount: '1', unit: '束', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: '厚揚げ', amount: '1', unit: '枚', countText: '', estimatedPriceText: 'チラシ価格' },
    ],
    steps: [
      '菜の花は塩ゆでして水にとり、絞って4cm幅に切る。',
      '厚揚げはひと口大に切ってフライパンで軽く焼く。',
      'だし汁・しょうゆ・みりんで煮汁を作り、厚揚げを2分煮て菜の花を加えてひと煮する。',
    ],
    reason: '菜の花の苦みは短時間調理で残しつつ、だし汁で和らぐ。',
  },
  {
    title: 'キャベツたっぷりお好み焼き',
    season: 'spring', genre: '和食', mainIngredient: '豚こま',
    summary: '春キャベツが甘くてふわふわ。小麦粉・卵・キャベツで完結。',
    servings: '2人前',
    estimatedTotalPrice: '',
    ingredients: [
      { name: '春キャベツ', amount: '1/4', unit: '玉', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: '豚こま切れ', amount: '100', unit: 'g', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: '卵', amount: '2', unit: '個', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: '薄力粉', amount: '80', unit: 'g', countText: '', estimatedPriceText: 'チラシ価格' },
    ],
    steps: [
      'キャベツは千切り。薄力粉・卵・水100ml・だし粉を混ぜて生地を作る。',
      'キャベツと豚こまを生地に加えてよく混ぜる。',
      'フライパンに油を引き、中火で蓋をして5分焼いて裏返し、さらに5分。',
      'ソース・マヨネーズ・青のりをかけて完成。',
    ],
    reason: '春キャベツは甘みと水分が多く、ふんわりした生地に仕上がる。',
  },
  {
    title: '豚こまとそら豆の卵とじ',
    season: 'spring', genre: '和食', mainIngredient: '豚こま',
    summary: '鮮やかな緑と卵のやわらかさが春らしい主菜。',
    servings: '2人前',
    estimatedTotalPrice: '',
    ingredients: [
      { name: '豚こま切れ', amount: '120', unit: 'g', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: 'そら豆', amount: '15', unit: '粒', countText: '1パック想定', estimatedPriceText: 'チラシ価格' },
      { name: '卵', amount: '3', unit: '個', countText: '', estimatedPriceText: 'チラシ価格' },
    ],
    steps: [
      'そら豆は塩ゆでして薄皮をむく。',
      'フライパンで豚こまを炒め、だし汁・しょうゆ・みりんを加える。',
      'そら豆を加えて溶き卵を回しかけ、半熟で火を止める。',
    ],
    reason: '旬のそら豆はゆでるだけで甘みが出て、卵と相性がいい。',
  },
  {
    title: '豚こまと新じゃがの炒め煮',
    season: 'spring', genre: '和食', mainIngredient: '豚こま',
    summary: '新じゃがのほくほく感が楽しい春のおかず。',
    servings: '2人前',
    estimatedTotalPrice: '',
    ingredients: [
      { name: '豚こま切れ', amount: '150', unit: 'g', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: '新じゃがいも', amount: '300', unit: 'g', countText: '小ぶり4〜5個', estimatedPriceText: 'チラシ価格' },
    ],
    steps: [
      '新じゃがは皮付きのまま半分に切り、電子レンジで4分加熱する。',
      'フライパンで豚こまを炒め、じゃがいもを加える。',
      'しょうゆ・みりん・砂糖各大さじ1で調味し、汁気が飛ぶまで炒め煮にする。',
    ],
    reason: '新じゃがは皮ごと使えて栄養も旨みも逃さない。',
  },

  // ── 夏（6〜8月） ─────────────────────────────────────────────────────
  {
    title: 'ゴーヤと豚こまの卵炒め',
    season: 'summer', genre: '和食', mainIngredient: '豚こま',
    summary: '苦みをやわらげながらスタミナを補う、夏の定番。',
    servings: '2人前',
    estimatedTotalPrice: '',
    ingredients: [
      { name: '豚こま切れ', amount: '150', unit: 'g', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: 'ゴーヤ', amount: '1/2', unit: '本', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: '卵', amount: '2', unit: '個', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: '木綿豆腐', amount: '1/2', unit: '丁', countText: '', estimatedPriceText: 'チラシ価格' },
    ],
    steps: [
      'ゴーヤは薄切りにして塩もみし、水でさっと洗って苦みを和らげる。',
      '豆腐はキッチンペーパーで水切りしてほぐす。',
      'フライパンで豚こまを炒め、ゴーヤ・豆腐を加える。',
      '塩・しょうゆで調味し、溶き卵を回しかけてさっと炒める。',
    ],
    reason: 'ゴーヤは薄切り塩もみで苦みが落ち着き、食べやすくなる。',
  },
  {
    title: 'ナスと豚ひき肉の味噌炒め',
    season: 'summer', genre: '和食', mainIngredient: '豚ひき',
    summary: '油を吸ったナスに甘辛味噌が絡む夏の定番おかず。',
    servings: '2人前',
    estimatedTotalPrice: '',
    ingredients: [
      { name: '豚ひき肉', amount: '150', unit: 'g', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: 'ナス', amount: '3', unit: '本', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: 'みそ', amount: '大さじ1.5', unit: '', countText: '', estimatedPriceText: 'チラシ価格' },
    ],
    steps: [
      'ナスは乱切りにして水にさらしてアクを抜く。',
      'フライパンに油を多めに熱し、ナスを炒めていったん取り出す。',
      '同じフライパンでひき肉を炒め、みそ・みりん・砂糖を加える。',
      'ナスを戻し入れてよく絡めて完成。',
    ],
    reason: 'ナスはいったん取り出すことでとろっとした食感が出る。',
  },
  {
    title: 'オクラの豚巻き',
    season: 'summer', genre: '和食', mainIngredient: '豚こま',
    summary: 'シャキシャキのオクラを豚こまで巻いてボリューム感を出す。',
    servings: '2人前',
    estimatedTotalPrice: '',
    ingredients: [
      { name: '豚こま切れ（大きめ）', amount: '200', unit: 'g', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: 'オクラ', amount: '10', unit: '本', countText: '1袋', estimatedPriceText: 'チラシ価格' },
    ],
    steps: [
      'オクラは塩で板ずりして洗う。',
      '豚こまを2〜3枚重ねてオクラに巻きつけ、塩こしょうする。',
      'フライパンで転がしながら全体に焼き色をつける。',
      'しょうゆ・みりん各大さじ1を加えて絡める。',
    ],
    reason: 'オクラは巻くことで食べ応えが出て、ねばりが豚肉に絡む。',
  },
  {
    title: '夏野菜と鶏むね肉の炒め物',
    season: 'summer', genre: '和食', mainIngredient: '鶏むね',
    summary: 'ズッキーニ・パプリカの彩りが鮮やかな、さっぱり炒め。',
    servings: '2人前',
    estimatedTotalPrice: '',
    ingredients: [
      { name: '鶏むね肉', amount: '1', unit: '枚', countText: '薄切り', estimatedPriceText: 'チラシ価格' },
      { name: 'ズッキーニ', amount: '1', unit: '本', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: 'パプリカ', amount: '1', unit: '個', countText: '', estimatedPriceText: 'チラシ価格' },
    ],
    steps: [
      '鶏むね肉は薄切りにして塩・酒・片栗粉で下味をつける。',
      'ズッキーニ・パプリカは食べやすく切る。',
      'フライパンで鶏肉を炒め、野菜を加えて強火で炒める。',
      '塩・こしょう・しょうゆ少量で味をまとめる。',
    ],
    reason: '鶏むね肉に片栗粉をつけると、炒めてもしっとりした食感になる。',
  },
  {
    title: 'トマトと卵の中華炒め',
    season: 'summer', genre: '中華', mainIngredient: '卵',
    summary: '酸味と甘みのバランスがクセになる、中国家庭料理の定番。',
    servings: '2人前',
    estimatedTotalPrice: '',
    ingredients: [
      { name: 'トマト', amount: '2', unit: '個', countText: '完熟が理想', estimatedPriceText: 'チラシ価格' },
      { name: '卵', amount: '3', unit: '個', countText: '', estimatedPriceText: 'チラシ価格' },
    ],
    steps: [
      '卵は溶いて塩を加える。トマトはざく切りにする。',
      'フライパンに油を多めに熱し、卵をふんわり炒めていったん取り出す。',
      '同じフライパンでトマトを炒め、砂糖・塩・鶏ガラスープの素で味をつける。',
      '卵を戻し入れてさっと混ぜて完成。',
    ],
    reason: 'トマトの酸みが卵でまろやかになり、ご飯が進む組み合わせ。',
  },
  {
    title: '豚しゃぶとたっぷり野菜の冷しゃぶ',
    season: 'summer', genre: '和食', mainIngredient: '豚しゃぶ',
    summary: 'ゆでて冷やすだけ。タレは市販でOKのさっぱり夏おかず。',
    servings: '2人前',
    estimatedTotalPrice: '',
    ingredients: [
      { name: '豚しゃぶ用薄切り肉', amount: '200', unit: 'g', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: 'レタス', amount: '1/2', unit: '玉', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: 'きゅうり', amount: '1', unit: '本', countText: '', estimatedPriceText: 'チラシ価格' },
    ],
    steps: [
      '豚肉を沸騰した湯でさっとゆで、冷水にとって冷やす。',
      'レタスは手でちぎり、きゅうりは薄切りにする。',
      '皿に野菜を広げ、豚肉を盛る。',
      'ポン酢やごまだれをかけて完成。',
    ],
    reason: '豚しゃぶは火を通しすぎず、冷水でしめると柔らかく仕上がる。',
  },
  {
    title: 'ピーマンと豚肉の細切り炒め（青椒肉絲風）',
    season: 'summer', genre: '中華', mainIngredient: '豚ロース',
    summary: 'ピーマン最盛期に合わせた、シンプルな中華炒め。',
    servings: '2人前',
    estimatedTotalPrice: '',
    ingredients: [
      { name: '豚ロース薄切り', amount: '150', unit: 'g', countText: '細切り', estimatedPriceText: 'チラシ価格' },
      { name: 'ピーマン', amount: '4', unit: '個', countText: '細切り', estimatedPriceText: 'チラシ価格' },
      { name: 'たけのこ水煮', amount: '50', unit: 'g', countText: '細切り', estimatedPriceText: 'チラシ価格' },
    ],
    steps: [
      '豚肉は細切りにして酒・しょうゆ・片栗粉で下味をつける。',
      'フライパンで豚肉を炒めていったん取り出す。',
      '同じフライパンでピーマン・たけのこを炒め、豚肉を戻す。',
      'オイスターソース・しょうゆで調味して完成。',
    ],
    reason: '夏のピーマンは甘みが強く、細切りにすると苦みが和らぐ。',
  },

  // ── 秋（9〜11月） ────────────────────────────────────────────────────
  {
    title: 'きのこたっぷり炊き込みご飯',
    season: 'fall', genre: '和食', mainIngredient: '豆腐',
    summary: 'しいたけ・えのき・しめじを使った香り豊かな秋のご飯。',
    servings: '2人前',
    estimatedTotalPrice: '',
    ingredients: [
      { name: '米', amount: '2', unit: '合', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: 'しいたけ・しめじ・えのき合わせ', amount: '200', unit: 'g', countText: '好みで', estimatedPriceText: 'チラシ価格' },
      { name: '油揚げ', amount: '1', unit: '枚', countText: '', estimatedPriceText: 'チラシ価格' },
    ],
    steps: [
      'きのこは石づきを除いてほぐし、油揚げは細切りにする。',
      '米を研いで炊飯器に入れ、しょうゆ・みりん・酒各大さじ1と水を規定量まで加える。',
      'きのこと油揚げをのせて炊く。',
      '炊き上がったらさっくり混ぜて盛る。',
    ],
    reason: 'きのこは種類を混ぜると香りと食感に奥行きが出る。',
  },
  {
    title: 'さつまいもと豚こまの甘煮',
    season: 'fall', genre: '和食', mainIngredient: '豚こま',
    summary: 'さつまいもの甘みが豚肉に絡む、弁当にも使えるおかず。',
    servings: '2人前',
    estimatedTotalPrice: '',
    ingredients: [
      { name: '豚こま切れ', amount: '150', unit: 'g', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: 'さつまいも', amount: '1', unit: '本', countText: '中サイズ', estimatedPriceText: 'チラシ価格' },
    ],
    steps: [
      'さつまいもは2cm厚さの輪切りにして水にさらす。',
      'フライパンで豚こまを炒め、水気を切ったさつまいもを加える。',
      'だし汁100ml・しょうゆ・みりん・砂糖各大さじ1を加えて蓋をして煮る。',
      '汁気が少なくなったら蓋を外してとろみをつけて完成。',
    ],
    reason: 'さつまいもは水にさらすことでアクが抜け、ホクホクに煮える。',
  },
  {
    title: '秋鮭ときのこのホイル焼き',
    season: 'fall', genre: '和食', mainIngredient: '魚',
    summary: '旬の秋鮭をオーブンやフライパンで手軽に仕上げる一皿。',
    servings: '2人前',
    estimatedTotalPrice: '',
    ingredients: [
      { name: '生鮭', amount: '2', unit: '切れ', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: 'しめじ・えのきなど', amount: '1', unit: 'パック', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: 'バター', amount: '10', unit: 'g', countText: '', estimatedPriceText: 'チラシ価格' },
    ],
    steps: [
      '鮭に塩こしょうをふる。きのこはほぐす。',
      'アルミホイルに鮭・きのこを乗せ、バターをのせてポン酢を少量かける。',
      'ホイルを閉じてフライパンに入れ、蓋をして中火で10〜12分蒸し焼きにする。',
      'ホイルを開けてそのままテーブルへ。',
    ],
    reason: 'ホイル焼きは洗い物が少なく、蒸し焼きで鮭がふっくら仕上がる。',
  },
  {
    title: 'れんこんと豚こまのきんぴら',
    season: 'fall', genre: '和食', mainIngredient: '豚こま',
    summary: 'シャキッとしたれんこんの食感が楽しい常備菜にもなるおかず。',
    servings: '2人前',
    estimatedTotalPrice: '',
    ingredients: [
      { name: '豚こま切れ', amount: '100', unit: 'g', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: 'れんこん', amount: '200', unit: 'g', countText: '', estimatedPriceText: 'チラシ価格' },
    ],
    steps: [
      'れんこんは薄切りにして水にさらす。',
      'フライパンでごま油を熱し、豚こまを炒める。',
      'れんこんを加えて炒め、しょうゆ・みりん各大さじ1と砂糖小さじ1で調味する。',
      '仕上げに白ごまをふる。',
    ],
    reason: 'れんこんは水にさらすと変色を防ぎ、シャキッとした食感が出る。',
  },
  {
    title: 'かぼちゃと豚こまの煮物',
    season: 'fall', genre: '和食', mainIngredient: '豚こま',
    summary: 'かぼちゃの甘みが染みた、ほっこりする秋の定番おかず。',
    servings: '2人前',
    estimatedTotalPrice: '',
    ingredients: [
      { name: '豚こま切れ', amount: '120', unit: 'g', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: 'かぼちゃ', amount: '1/4', unit: '個', countText: '300g程度', estimatedPriceText: 'チラシ価格' },
    ],
    steps: [
      'かぼちゃは3cm角に切る。豚こまは食べやすく切る。',
      '鍋にだし汁200ml・しょうゆ・みりん・砂糖各大さじ1を入れて煮立てる。',
      '豚こまとかぼちゃを入れ、蓋をして中火で10〜12分煮る。',
      '汁気が少なくなったら完成。',
    ],
    reason: 'かぼちゃは火を通すと甘みが増し、少ない調味料で味が決まる。',
  },
  {
    title: 'ごぼうと鶏肉のきんぴら',
    season: 'fall', genre: '和食', mainIngredient: '鶏もも',
    summary: '歯ごたえと旨みが詰まった、日持ちのする秋の常備菜。',
    servings: '2人前',
    estimatedTotalPrice: '',
    ingredients: [
      { name: '鶏もも肉', amount: '1/2', unit: '枚', countText: '細切り', estimatedPriceText: 'チラシ価格' },
      { name: 'ごぼう', amount: '1', unit: '本', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: 'にんじん', amount: '1/2', unit: '本', countText: '', estimatedPriceText: 'チラシ価格' },
    ],
    steps: [
      'ごぼうはささがき、にんじんは細切り、鶏肉は細切りにする。',
      'フライパンにごま油を熱し、鶏肉を炒める。',
      'ごぼう・にんじんを加えて炒め、しょうゆ・みりん・砂糖で甘辛く調味する。',
      '汁気がほぼなくなったら完成。',
    ],
    reason: 'ごぼうは旬の秋に香りが強く、きんぴらにすると日持ちする。',
  },
  {
    title: '里芋と鶏肉の煮物',
    season: 'fall', genre: '和食', mainIngredient: '鶏もも',
    summary: 'とろっとした里芋と鶏肉の旨みが合わさる秋冬のおかず。',
    servings: '2人前',
    estimatedTotalPrice: '',
    ingredients: [
      { name: '鶏もも肉', amount: '1', unit: '枚', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: '里芋', amount: '6', unit: '個', countText: '冷凍でも可', estimatedPriceText: 'チラシ価格' },
    ],
    steps: [
      '里芋は電子レンジで3分加熱してから皮をむく（冷凍は解凍不要）。',
      '鶏肉はひと口大に切る。',
      '鍋にだし汁・しょうゆ・みりん各大さじ2を煮立て、鶏肉と里芋を加える。',
      '蓋をして12分煮て、仕上げに煮汁を少し詰める。',
    ],
    reason: '里芋の冷凍品を使うと皮むきの手間がなく平日でも気軽に作れる。',
  },
  {
    title: 'さんまの大根おろしポン酢',
    season: 'fall', genre: '和食', mainIngredient: '魚',
    summary: '旬のさんまを焼いてポン酢でさっぱりと食べる秋の定番。',
    servings: '2人前',
    estimatedTotalPrice: '',
    ingredients: [
      { name: 'さんま', amount: '2', unit: '尾', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: '大根', amount: '1/4', unit: '本', countText: 'おろす', estimatedPriceText: 'チラシ価格' },
    ],
    steps: [
      'さんまはペーパーで水気をふき、塩を振って10分おく。',
      'グリルまたはフライパンで両面こんがり焼く（7〜8分）。',
      '大根をすりおろして水気を軽く切る。',
      '皿に盛り、大根おろしとポン酢をかけて完成。',
    ],
    reason: '旬のさんまは秋に脂が乗り、シンプルに塩焼きするだけで旨い。',
  },

  // ── 冬（12〜2月） ────────────────────────────────────────────────────
  {
    title: '白菜と豚肉のミルフィーユ蒸し',
    season: 'winter', genre: '和食', mainIngredient: '豚バラ',
    summary: '白菜と豚肉を重ねて蒸すだけ。ポン酢でさっぱり食べる冬の鍋風一品。',
    servings: '2人前',
    estimatedTotalPrice: '',
    ingredients: [
      { name: '豚バラ薄切り', amount: '200', unit: 'g', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: '白菜', amount: '1/4', unit: '玉', countText: '', estimatedPriceText: 'チラシ価格' },
    ],
    steps: [
      '白菜は4cm幅に切る。豚バラは白菜と同じ幅に切る。',
      '鍋に白菜・豚バラを交互に重ね、塩を全体に振る。',
      '酒大さじ2を回しかけ、蓋をして中火で12〜15分蒸す。',
      '皿に盛りポン酢をかけて完成。',
    ],
    reason: '重ね蒸しは白菜から水分が出て、だし不要で旨みが出る。',
  },
  {
    title: '大根と手羽先の煮物',
    season: 'winter', genre: '和食', mainIngredient: '手羽先',
    summary: '手羽先のコラーゲンが染み出た、とろっとした大根の煮物。',
    servings: '2人前',
    estimatedTotalPrice: '',
    ingredients: [
      { name: '手羽先', amount: '6', unit: '本', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: '大根', amount: '1/3', unit: '本', countText: '', estimatedPriceText: 'チラシ価格' },
    ],
    steps: [
      '大根は2cm輪切りにして面取りし、下ゆでする（電子レンジ5分でも可）。',
      '手羽先を鍋で焼き色をつける。',
      '大根を加え、水・しょうゆ・みりん・砂糖で落とし蓋をして20分煮る。',
      '煮汁を少し詰めて完成。',
    ],
    reason: '手羽先は骨から出るゼラチンが大根に染みて深い味わいになる。',
  },
  {
    title: '豚汁',
    season: 'winter', genre: '和食', mainIngredient: '豚こま',
    summary: '根菜と豚肉が入った体の芯から温まる汁物。おかずと一品で完結。',
    servings: '2人前',
    estimatedTotalPrice: '',
    ingredients: [
      { name: '豚こま切れ', amount: '100', unit: 'g', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: '大根・にんじん・ごぼう・こんにゃく', amount: '各適量', unit: '', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: 'みそ', amount: '大さじ2', unit: '', countText: '', estimatedPriceText: 'チラシ価格' },
    ],
    steps: [
      '根菜は乱切り、こんにゃくはひと口大にちぎる。',
      '鍋でごま油を熱し、豚こまと根菜を炒める。',
      '水600mlを加えて根菜が柔らかくなるまで煮る（10〜15分）。',
      'みそを溶き入れて完成。',
    ],
    reason: '根菜を炒めてから煮ることで旨みが出やすく、香りもいい。',
  },
  {
    title: 'ほうれん草とベーコンのグラタン',
    season: 'winter', genre: '洋食', mainIngredient: '豚バラ',
    summary: 'バター・小麦粉・牛乳でシンプルなホワイトソースを作る冬のグラタン。',
    servings: '2人前',
    estimatedTotalPrice: '',
    ingredients: [
      { name: 'ほうれん草', amount: '1', unit: '束', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: 'ベーコン', amount: '3', unit: '枚', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: '牛乳', amount: '300', unit: 'ml', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: 'バター・薄力粉', amount: '各大さじ1.5', unit: '', countText: '', estimatedPriceText: 'チラシ価格' },
    ],
    steps: [
      'ほうれん草はゆでて4cm幅に切る。ベーコンは細切り。',
      '鍋でバターを溶かし薄力粉を炒め、牛乳を少しずつ加えてソースを作る。',
      '塩・こしょうで調味し、ほうれん草・ベーコンを加えてグラタン皿に入れる。',
      'チーズを乗せてトースターで15分焼く。',
    ],
    reason: 'ほうれん草はゆでて絞ると苦みが抜け、ソースとなじみやすくなる。',
  },
  {
    title: '小松菜と厚揚げの煮浸し',
    season: 'winter', genre: '和食', mainIngredient: '豆腐',
    summary: '出汁が染みた厚揚げと小松菜の、手軽で体にやさしい副菜。',
    servings: '2人前',
    estimatedTotalPrice: '',
    ingredients: [
      { name: '小松菜', amount: '1', unit: '束', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: '厚揚げ', amount: '1', unit: '枚', countText: '', estimatedPriceText: 'チラシ価格' },
    ],
    steps: [
      '小松菜は4cm幅、厚揚げはひと口大に切る。',
      'フライパンにだし汁200ml・しょうゆ・みりん各大さじ1を入れて煮立てる。',
      '厚揚げを入れて3分煮てから小松菜を加え、さっと煮て完成。',
    ],
    reason: '厚揚げは先に煮ることでだし汁を吸い、小松菜は後入れで色を保つ。',
  },
  {
    title: 'かぶと鶏ひき肉のとろみ煮',
    season: 'winter', genre: '和食', mainIngredient: '鶏ひき',
    summary: 'かぶのやわらかさと鶏ひき肉の旨みがとろとろに絡む一品。',
    servings: '2人前',
    estimatedTotalPrice: '',
    ingredients: [
      { name: '鶏ひき肉', amount: '150', unit: 'g', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: 'かぶ', amount: '3', unit: '個', countText: '葉も使う', estimatedPriceText: 'チラシ価格' },
    ],
    steps: [
      'かぶは4等分に切り、葉は4cm幅に切る。',
      'フライパンでひき肉を炒め、だし汁200mlを加える。',
      'かぶを加えて柔らかくなるまで煮る（5〜7分）。',
      'しょうゆ・みりん各大さじ1で調味し、水溶き片栗粉でとろみをつける。かぶの葉を加えてひと煮して完成。',
    ],
    reason: 'かぶは火の通りが早く、葉ごと使うと栄養も逃さない。',
  },
  {
    title: '根菜たっぷりけんちん汁',
    season: 'winter', genre: '和食', mainIngredient: '豆腐',
    summary: '体の中から温まる精進料理のような一椀。具だくさんで腹持ちもいい。',
    servings: '2人前',
    estimatedTotalPrice: '',
    ingredients: [
      { name: '木綿豆腐', amount: '1/2', unit: '丁', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: '大根・にんじん・ごぼう・こんにゃく', amount: '各適量', unit: '', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: 'みそ', amount: '大さじ2', unit: '', countText: '', estimatedPriceText: 'チラシ価格' },
    ],
    steps: [
      '豆腐は手でくずしてペーパーで水気を取る。根菜は乱切り。',
      '鍋にごま油を熱し、豆腐を炒めて崩す。根菜を加えて炒める。',
      '水600mlを注いで根菜が柔らかくなるまで煮る。',
      'みそを溶き入れて仕上げる。',
    ],
    reason: '豆腐を炒めることで崩れにくく、旨みが出やすくなる。',
  },
  {
    title: '白菜と豚こまのとろとろ塩鍋',
    season: 'winter', genre: '和食', mainIngredient: '豚こま',
    summary: '白菜の甘みと豚肉の旨みだけで成立する、ごくシンプルな鍋もの。',
    servings: '2人前',
    estimatedTotalPrice: '',
    ingredients: [
      { name: '豚こま切れ', amount: '200', unit: 'g', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: '白菜', amount: '1/4', unit: '玉', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: '豆腐', amount: '1/2', unit: '丁', countText: 'お好みで', estimatedPriceText: 'チラシ価格' },
    ],
    steps: [
      '白菜はざく切り、豆腐はひと口大に切る。',
      '土鍋（またはフライパン）に水500mlと鶏ガラスープの素小さじ2を入れて煮立てる。',
      '豚こまと白菜、豆腐を入れて蓋をして中火で10分煮る。',
      '塩・こしょうで味を整えてポン酢や好みのたれで食べる。',
    ],
    reason: '白菜は煮ると水分が出てくるため、水は控えめにしてもよい。',
  },

  // ── 通年 ──────────────────────────────────────────────────────────────
  {
    title: '鶏もも肉の照り焼き',
    season: 'all', genre: '和食', mainIngredient: '鶏もも',
    summary: 'ご飯が進む甘辛の照り焼きは、平日の献立を決める定番おかず。',
    servings: '2人前',
    estimatedTotalPrice: '',
    ingredients: [
      { name: '鶏もも肉', amount: '2', unit: '枚', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: 'しょうゆ・みりん・酒', amount: '各大さじ2', unit: '', countText: '', estimatedPriceText: 'チラシ価格' },
    ],
    steps: [
      '鶏肉は厚みのある部分に切り込みを入れて均一にし、塩こしょうをふる。',
      'フライパンに油を熱し、皮目から中火で7〜8分焼く。',
      'ひっくり返して3分焼き、たれ（しょうゆ・みりん・酒）を加えて絡める。',
      'たれがとろっとしたら完成。',
    ],
    reason: '皮目をしっかり焼くとパリッとした食感と香ばしさが出る。',
  },
  {
    title: '肉豆腐',
    season: 'all', genre: '和食', mainIngredient: '豆腐',
    summary: '甘辛の煮汁が豆腐に染みた、ご飯のお供になるおかず。',
    servings: '2人前',
    estimatedTotalPrice: '',
    ingredients: [
      { name: '牛こま切れ（または豚）', amount: '150', unit: 'g', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: '木綿豆腐', amount: '1', unit: '丁', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: '玉ねぎ', amount: '1', unit: '個', countText: '', estimatedPriceText: 'チラシ価格' },
    ],
    steps: [
      '豆腐は食べやすく切り、玉ねぎはくし切りにする。',
      'フライパンで肉を炒め、玉ねぎを加えてしんなりさせる。',
      'だし汁200ml・しょうゆ・みりん各大さじ2・砂糖小さじ2を加える。',
      '豆腐を入れて蓋をして8分煮て完成。',
    ],
    reason: '木綿豆腐は煮崩れしにくく、しっかりとだし汁を吸う。',
  },
  {
    title: '鶏むね肉の親子丼',
    season: 'all', genre: '和食', mainIngredient: '鶏むね',
    summary: '鶏むね肉でもしっとり仕上がる、コスパ最高の一皿。',
    servings: '2人前',
    estimatedTotalPrice: '',
    ingredients: [
      { name: '鶏むね肉', amount: '1', unit: '枚', countText: '薄切り', estimatedPriceText: 'チラシ価格' },
      { name: '卵', amount: '4', unit: '個', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: '玉ねぎ', amount: '1', unit: '個', countText: '薄切り', estimatedPriceText: 'チラシ価格' },
    ],
    steps: [
      '鶏むね肉は薄切りにして酒・片栗粉で下味をつける。',
      '丼用の鍋にだし汁200ml・しょうゆ・みりん各大さじ2を煮立て、玉ねぎを加える。',
      '鶏肉を加えて火が通ったら溶き卵を回しかけ、半熟で蓋をして蒸らす。',
      'ご飯に盛って完成。',
    ],
    reason: '鶏むね肉は片栗粉で下処理するとしっとり柔らかく仕上がる。',
  },
  {
    title: '豚こまと玉ねぎの生姜焼き',
    season: 'all', genre: '和食', mainIngredient: '豚こま',
    summary: '定食の定番。玉ねぎと豚こまで手軽に作れる生姜焼き。',
    servings: '2人前',
    estimatedTotalPrice: '',
    ingredients: [
      { name: '豚こま切れ', amount: '200', unit: 'g', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: '玉ねぎ', amount: '1', unit: '個', countText: '薄切り', estimatedPriceText: 'チラシ価格' },
      { name: 'しょうが', amount: '1', unit: 'かけ', countText: 'すりおろし', estimatedPriceText: 'チラシ価格' },
    ],
    steps: [
      '豚こまはしょうゆ・みりん・しょうがで5分漬ける。',
      'フライパンに油を熱し、玉ねぎを炒めてしんなりさせる。',
      '豚こまをたれごと加えて炒め、汁気がなくなるまで炒め続ける。',
      '千切りキャベツと一緒に盛る。',
    ],
    reason: 'こま切れ肉は下漬けすることで短時間でも味がしっかりなじむ。',
  },
  {
    title: '豚こまともやしの中華炒め',
    season: 'all', genre: '中華', mainIngredient: '豚こま',
    summary: '5分で仕上がる時短メニュー。もやしのシャキシャキ感が命。',
    servings: '2人前',
    estimatedTotalPrice: '',
    ingredients: [
      { name: '豚こま切れ', amount: '150', unit: 'g', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: 'もやし', amount: '1', unit: '袋', countText: '200g', estimatedPriceText: 'チラシ価格' },
      { name: 'にら', amount: '1/2', unit: '束', countText: 'お好みで', estimatedPriceText: 'チラシ価格' },
    ],
    steps: [
      '豚こまは塩こしょうをふる。にらは4cm幅に切る。',
      'フライパンに油を熱し、豚こまを炒めて取り出す。',
      'もやしを強火でさっと炒め、豚こまを戻し、にらを加える。',
      'しょうゆ・オイスターソース各小さじ1・ごま油少量で味をまとめる。',
    ],
    reason: 'もやしは強火で短時間炒めることでシャキッとした食感が出る。',
  },
  {
    title: '麻婆豆腐（家庭版）',
    season: 'all', genre: '中華', mainIngredient: '豚ひき',
    summary: '豆板醤の辛みと豆腐のやさしさが合わさる人気のおかず。辛さは調整可。',
    servings: '2人前',
    estimatedTotalPrice: '',
    ingredients: [
      { name: '豚ひき肉', amount: '150', unit: 'g', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: '木綿豆腐', amount: '1', unit: '丁', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: '豆板醤', amount: '小さじ1', unit: '', countText: '辛さで加減', estimatedPriceText: 'チラシ価格' },
    ],
    steps: [
      '豆腐は2cm角に切り、熱湯で1分下ゆでして水気を切る。',
      'フライパンにごま油を熱し、にんにく・しょうがを炒め、ひき肉と豆板醤を加える。',
      '鶏ガラスープ150ml・しょうゆ・みりん各大さじ1を加えて煮立てる。',
      '豆腐を入れて3分煮て、水溶き片栗粉でとろみをつけて完成。',
    ],
    reason: '豆腐を下ゆですると崩れにくく、しっかり旨みを吸う。',
  },
  {
    title: '厚揚げと豚こまの甘辛煮',
    season: 'all', genre: '和食', mainIngredient: '豚こま',
    summary: '厚揚げが旨みを吸って満足感のある一皿。豆腐系の中で一番腹持ちがいい。',
    servings: '2人前',
    estimatedTotalPrice: '',
    ingredients: [
      { name: '豚こま切れ', amount: '120', unit: 'g', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: '厚揚げ', amount: '1', unit: '枚', countText: '大きめ', estimatedPriceText: 'チラシ価格' },
    ],
    steps: [
      '厚揚げはひと口大に切る。豚こまは塩こしょうをふる。',
      'フライパンで豚こまを炒め、厚揚げを加えて焼き色をつける。',
      'しょうゆ・みりん各大さじ1.5・砂糖小さじ1を加えて全体に絡める。',
      '汁気が少なくなったら完成。',
    ],
    reason: '厚揚げは先に軽く焼くと、たれがよく染みて表面がとろっとする。',
  },
  {
    title: '鶏むね肉のレモン蒸し',
    season: 'all', genre: '洋食', mainIngredient: '鶏むね',
    summary: 'さっぱりレモン風味で飽きずに食べられる、ヘルシーなおかず。',
    servings: '2人前',
    estimatedTotalPrice: '',
    ingredients: [
      { name: '鶏むね肉', amount: '1', unit: '枚', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: 'レモン', amount: '1/2', unit: '個', countText: 'スライス', estimatedPriceText: 'チラシ価格' },
    ],
    steps: [
      '鶏むね肉は厚さを均一にして塩・こしょう・酒をふる。',
      'フライパンに鶏肉を皮目から入れ、レモンスライスをのせて蓋をする。',
      '中火で8〜10分蒸し焼きにして、ひっくり返してさらに3分。',
      '切って盛り、汁をかけて完成。',
    ],
    reason: 'レモンの酸みが脂を和らげ、あっさり食べやすくなる。',
  },
  {
    title: '豆腐と卵の中華スープ',
    season: 'all', genre: '中華', mainIngredient: '豆腐',
    summary: 'ふわっとした卵と豆腐が優しい、5分で作れる主食にもなるスープ。',
    servings: '2人前',
    estimatedTotalPrice: '',
    ingredients: [
      { name: '絹ごし豆腐', amount: '1/2', unit: '丁', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: '卵', amount: '2', unit: '個', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: '長ねぎ', amount: '1/3', unit: '本', countText: '', estimatedPriceText: 'チラシ価格' },
    ],
    steps: [
      '鍋に水400ml・鶏ガラスープの素小さじ1.5を入れて煮立てる。',
      '豆腐をスプーンでくずしながら加える。',
      '水溶き片栗粉少量でとろみをつけ、溶き卵を細く回しかける。',
      '塩・こしょうで調味し、ねぎと胡麻油で仕上げる。',
    ],
    reason: 'とろみをつけてから卵を加えると、ふんわり均一に広がる。',
  },
  {
    title: '鶏ひき肉と豆腐のとろみ煮',
    season: 'all', genre: '和食', mainIngredient: '鶏ひき',
    summary: '鶏ひき肉のあっさりした旨みが豆腐に絡む、やさしい主菜。',
    servings: '2人前',
    estimatedTotalPrice: '',
    ingredients: [
      { name: '鶏ひき肉', amount: '150', unit: 'g', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: '絹ごし豆腐', amount: '1', unit: '丁', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: '長ねぎ', amount: '1/2', unit: '本', countText: '斜め切り', estimatedPriceText: 'チラシ価格' },
    ],
    steps: [
      'フライパンでひき肉を炒め、しょうがを加えてほぐす。',
      'だし汁200ml・しょうゆ・みりん各大さじ1.5を加えて煮立てる。',
      '豆腐をスプーンでくずしながら加え、ねぎも加えて3分煮る。',
      '水溶き片栗粉でとろみをつけて完成。',
    ],
    reason: 'ひき肉は細かいから豆腐と馴染みやすく、とろみと合うと食べやすい。',
  },
  {
    title: '豚こまとキャベツの味噌炒め',
    season: 'all', genre: '和食', mainIngredient: '豚こま',
    summary: '豚とキャベツは鉄板の組み合わせ。味噌がご飯によく合う。',
    servings: '2人前',
    estimatedTotalPrice: '',
    ingredients: [
      { name: '豚こま切れ', amount: '180', unit: 'g', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: 'キャベツ', amount: '1/4', unit: '玉', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: 'みそ', amount: '大さじ1.5', unit: '', countText: '', estimatedPriceText: 'チラシ価格' },
    ],
    steps: [
      'キャベツはざく切り、豚こまは食べやすく切る。',
      'フライパンで豚こまを炒め、キャベツを加えてしんなりするまで炒める。',
      'みそ・みりん各大さじ1.5・砂糖小さじ1を合わせて加え、全体に絡める。',
    ],
    reason: '豚とキャベツはビタミンB1の吸収が高まる理想的な組み合わせ。',
  },
  {
    title: 'さばの味噌煮',
    season: 'all', genre: '和食', mainIngredient: '魚',
    summary: '臭みを取る下処理さえすれば、あとは煮るだけの和食の定番。',
    servings: '2人前',
    estimatedTotalPrice: '',
    ingredients: [
      { name: 'さば', amount: '2', unit: '切れ', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: 'みそ', amount: '大さじ2', unit: '', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: 'しょうが', amount: '1', unit: 'かけ', countText: 'スライス', estimatedPriceText: 'チラシ価格' },
    ],
    steps: [
      'さばに熱湯をかけて霜降りし、水で洗って臭みを取る。',
      'フライパンに水・酒・みりん・砂糖各大さじ2を煮立て、しょうがとさばを入れる。',
      '落とし蓋をして中火で5分煮てからみそを溶き入れる。',
      'さらに5分煮詰めて完成。',
    ],
    reason: '霜降りをすることで生臭みが消え、みそがよく染みる。',
  },
  {
    title: '豚こまと大根の煮物',
    season: 'all', genre: '和食', mainIngredient: '豚こま',
    summary: '大根が豚の旨みをたっぷり吸った、冷めても美味しいおかず。',
    servings: '2人前',
    estimatedTotalPrice: '',
    ingredients: [
      { name: '豚こま切れ', amount: '150', unit: 'g', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: '大根', amount: '1/3', unit: '本', countText: '', estimatedPriceText: 'チラシ価格' },
    ],
    steps: [
      '大根は2cm幅の輪切りにして電子レンジで4分下処理する。',
      '鍋で豚こまを炒めて焼き色をつける。',
      'だし汁300ml・しょうゆ・みりん各大さじ2・砂糖小さじ1を加えて大根を煮る。',
      '15分煮て汁気が減ったら完成。',
    ],
    reason: '大根の下処理をレンジでするとコンロを使わずに素早く中まで火が通る。',
  },
  {
    title: '鮭の塩焼きと大根おろし',
    season: 'all', genre: '和食', mainIngredient: '魚',
    summary: 'シンプルでいちばん飽きない。大根おろしがさっぱりさせてくれる定番魚料理。',
    servings: '2人前',
    estimatedTotalPrice: '',
    ingredients: [
      { name: '生鮭', amount: '2', unit: '切れ', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: '大根', amount: '1/5', unit: '本', countText: 'おろす', estimatedPriceText: 'チラシ価格' },
    ],
    steps: [
      '鮭に塩を振って10分おき、ペーパーで水気をふく。',
      'グリルまたはフライパンで両面を焼く（7〜8分）。',
      '大根をすりおろして水気を軽く切る。',
      '皿に盛り、大根おろしとポン酢を添える。',
    ],
    reason: '塩を振って水気をふくひと手間で、臭みが抜けて皮もパリッとなる。',
  },
  {
    title: '玉子焼き',
    season: 'all', genre: '和食', mainIngredient: '卵',
    summary: 'だし入り卵焼きは弁当にも副菜にもなる万能おかず。',
    servings: '2人前',
    estimatedTotalPrice: '',
    ingredients: [
      { name: '卵', amount: '3', unit: '個', countText: '', estimatedPriceText: 'チラシ価格' },
    ],
    steps: [
      '卵を溶き、だし汁・みりん・砂糖・塩で調味する。',
      '玉子焼き器に油を薄く引いて熱し、卵液の1/3を流し込む。',
      '半熟になったら手前に巻き、奥に寄せてまた卵液を流し込んで巻く。',
      'これを繰り返して3回で完成。形を整えて切り分ける。',
    ],
    reason: 'だし汁を多めにするとふんわりやわらかく、甘みは好みで調整する。',
  },
  {
    title: '豚こまと卵のカレー炒め',
    season: 'all', genre: '洋食', mainIngredient: '豚こま',
    summary: 'カレー粉でパンチをきかせた、あと引く辛みのシンプルな炒め物。',
    servings: '2人前',
    estimatedTotalPrice: '',
    ingredients: [
      { name: '豚こま切れ', amount: '180', unit: 'g', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: '卵', amount: '2', unit: '個', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: '玉ねぎ', amount: '1/2', unit: '個', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: 'カレー粉', amount: '小さじ2', unit: '', countText: '', estimatedPriceText: 'チラシ価格' },
    ],
    steps: [
      '玉ねぎは薄切り、豚こまは塩こしょうをふる。',
      'フライパンで玉ねぎを炒め、豚こまを加えて火を通す。',
      'カレー粉とコンソメ少量を加えて炒め合わせる。',
      '溶き卵を回しかけてふんわり炒めて完成。',
    ],
    reason: 'カレー粉は最後に加えると香りが立ちやすい。',
  },
  {
    title: '豚こまとにんじんのきんぴら',
    season: 'all', genre: '和食', mainIngredient: '豚こま',
    summary: '常備菜の定番。にんじんの甘みと豚こまの旨みが合う。',
    servings: '2人前',
    estimatedTotalPrice: '',
    ingredients: [
      { name: '豚こま切れ', amount: '100', unit: 'g', countText: '', estimatedPriceText: 'チラシ価格' },
      { name: 'にんじん', amount: '1', unit: '本', countText: '千切り', estimatedPriceText: 'チラシ価格' },
    ],
    steps: [
      'にんじんは千切り、豚こまは細かく切る。',
      'フライパンでごま油を熱し、豚こまを炒める。',
      'にんじんを加えて炒め、しょうゆ・みりん各大さじ1・砂糖小さじ1で調味する。',
      '汁気が飛んだら白ごまをふって完成。',
    ],
    reason: 'にんじんは細く切ると早く火が通り、甘みが引き出される。',
  },
];

module.exports = RECIPE_LIBRARY;
